-- Create the token_status enum type
CREATE TYPE public.token_status AS ENUM ('waiting', 'serving', 'served', 'skipped');

-- Create the counters table
CREATE TABLE public.counters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true NOT NULL,
  current_token_id bigint, -- This will be a foreign key to tokens table, added later.
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Add RLS to the counters table
ALTER TABLE public.counters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to counters" ON public.counters FOR SELECT USING (true);
CREATE POLICY "Allow admins to manage counters" ON public.counters FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Create the tokens table
CREATE TABLE public.tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_number integer NOT NULL,
  counter_id bigint REFERENCES public.counters(id) ON DELETE CASCADE NOT NULL,
  status public.token_status DEFAULT 'waiting' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  served_at timestamptz
);

-- Add RLS to the tokens table
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to tokens" ON public.tokens FOR SELECT USING (true);
CREATE POLICY "Allow authenticated users to create tokens" ON public.tokens FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow admins to update tokens" ON public.tokens FOR UPDATE USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- Add the foreign key constraint from counters.current_token_id to tokens.id
ALTER TABLE public.counters
ADD CONSTRAINT fk_current_token
FOREIGN KEY (current_token_id)
REFERENCES public.tokens(id)
ON DELETE SET NULL;


-- Create the camera_data table
CREATE TABLE public.camera_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  counter_id bigint REFERENCES public.counters(id) ON DELETE CASCADE NOT NULL UNIQUE,
  people_count integer DEFAULT 0 NOT NULL,
  estimated_wait_time integer DEFAULT 0 NOT NULL, -- in minutes
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Add RLS to the camera_data table
ALTER TABLE public.camera_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to camera_data" ON public.camera_data FOR SELECT USING (true);
-- In a real-world scenario, you'd want a more secure policy, e.g., using a service_role key from a secure backend
CREATE POLICY "Allow service role to update camera data" ON public.camera_data FOR ALL USING (true) WITH CHECK (true);


-- Function to update the updated_at column on change
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for camera_data to automatically update updated_at timestamp
CREATE TRIGGER handle_updated_at_camera_data
  BEFORE UPDATE ON public.camera_data
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();

-- Insert some sample data for counters to get started
INSERT INTO public.counters (name, description) VALUES
('General Inquiry', 'For all general questions and information.'),
('Technical Support', 'For technical assistance and troubleshooting.'),
('Billing', 'For payments and billing inquiries.');

-- For each new counter, create a corresponding camera_data entry
INSERT INTO public.camera_data (counter_id)
SELECT id FROM public.counters;
